# Copyright 2025 InfluxData
# Author: Suyash Joshi (sjoshi@influxdata.com)

services:
  influxdb3-enterprise:
    container_name: influxdb3-enterprise
    image: quay.io/influxdb/influxdb3-enterprise:latest
    ports:
      - 8181:8181
    command:
      - serve
      - --node-id=${INFLUXDB_NODE_ID}
      - --cluster-id=${INFLUXDB_CLUSTER_ID}
      - --object-store=file
      - --data-dir=/var/lib/influxdb3
    volumes:
      - /mnt/data0/influxdb/data:/var/lib/influxdb3
      - /mnt/data0/influxdb/config:/etc/influxdb3
    environment:
      - INFLUXDB_ORG=${INFLUXDB_ORG}
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - /mnt/data0/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    depends_on:
      - influxdb3-enterprise
    restart: unless-stopped
